/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as MealBuilderRouteImport } from './routes/meal-builder'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about_v2'
import { Route as IndexRouteImport } from './routes/index_v2'
import { Route as ModulesIndexRouteImport } from './routes/modules.index'
import { Route as ModulesModuleIdQuizRouteImport } from './routes/modules.$moduleId.quiz'
import { Route as ModulesModuleIdLessonIdRouteImport } from './routes/modules.$moduleId.$lessonId'
import { Route as ApiPublicHooksCleanupOldUsersRouteImport } from './routes/api/public/hooks/cleanup-old-users'

const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const MealBuilderRoute = MealBuilderRouteImport.update({
  id: '/meal-builder',
  path: '/meal-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesIndexRoute = ModulesIndexRouteImport.update({
  id: '/modules/',
  path: '/modules/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesModuleIdQuizRoute = ModulesModuleIdQuizRouteImport.update({
  id: '/modules/$moduleId/quiz',
  path: '/modules/$moduleId/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesModuleIdLessonIdRoute = ModulesModuleIdLessonIdRouteImport.update({
  id: '/modules/$moduleId/$lessonId',
  path: '/modules/$moduleId/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksCleanupOldUsersRoute =
  ApiPublicHooksCleanupOldUsersRouteImport.update({
    id: '/api/public/hooks/cleanup-old-users',
    path: '/api/public/hooks/cleanup-old-users',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/meal-builder': typeof MealBuilderRoute
  '/progress': typeof ProgressRoute
  '/modules/': typeof ModulesIndexRoute
  '/modules/$moduleId/$lessonId': typeof ModulesModuleIdLessonIdRoute
  '/modules/$moduleId/quiz': typeof ModulesModuleIdQuizRoute
  '/api/public/hooks/cleanup-old-users': typeof ApiPublicHooksCleanupOldUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/meal-builder': typeof MealBuilderRoute
  '/progress': typeof ProgressRoute
  '/modules': typeof ModulesIndexRoute
  '/modules/$moduleId/$lessonId': typeof ModulesModuleIdLessonIdRoute
  '/modules/$moduleId/quiz': typeof ModulesModuleIdQuizRoute
  '/api/public/hooks/cleanup-old-users': typeof ApiPublicHooksCleanupOldUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/meal-builder': typeof MealBuilderRoute
  '/progress': typeof ProgressRoute
  '/modules/': typeof ModulesIndexRoute
  '/modules/$moduleId/$lessonId': typeof ModulesModuleIdLessonIdRoute
  '/modules/$moduleId/quiz': typeof ModulesModuleIdQuizRoute
  '/api/public/hooks/cleanup-old-users': typeof ApiPublicHooksCleanupOldUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/dashboard'
    | '/meal-builder'
    | '/progress'
    | '/modules/'
    | '/modules/$moduleId/$lessonId'
    | '/modules/$moduleId/quiz'
    | '/api/public/hooks/cleanup-old-users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/dashboard'
    | '/meal-builder'
    | '/progress'
    | '/modules'
    | '/modules/$moduleId/$lessonId'
    | '/modules/$moduleId/quiz'
    | '/api/public/hooks/cleanup-old-users'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/dashboard'
    | '/meal-builder'
    | '/progress'
    | '/modules/'
    | '/modules/$moduleId/$lessonId'
    | '/modules/$moduleId/quiz'
    | '/api/public/hooks/cleanup-old-users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  MealBuilderRoute: typeof MealBuilderRoute
  ProgressRoute: typeof ProgressRoute
  ModulesIndexRoute: typeof ModulesIndexRoute
  ModulesModuleIdLessonIdRoute: typeof ModulesModuleIdLessonIdRoute
  ModulesModuleIdQuizRoute: typeof ModulesModuleIdQuizRoute
  ApiPublicHooksCleanupOldUsersRoute: typeof ApiPublicHooksCleanupOldUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meal-builder': {
      id: '/meal-builder'
      path: '/meal-builder'
      fullPath: '/meal-builder'
      preLoaderRoute: typeof MealBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/': {
      id: '/modules/'
      path: '/modules'
      fullPath: '/modules/'
      preLoaderRoute: typeof ModulesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/$moduleId/quiz': {
      id: '/modules/$moduleId/quiz'
      path: '/modules/$moduleId/quiz'
      fullPath: '/modules/$moduleId/quiz'
      preLoaderRoute: typeof ModulesModuleIdQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/$moduleId/$lessonId': {
      id: '/modules/$moduleId/$lessonId'
      path: '/modules/$moduleId/$lessonId'
      fullPath: '/modules/$moduleId/$lessonId'
      preLoaderRoute: typeof ModulesModuleIdLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/cleanup-old-users': {
      id: '/api/public/hooks/cleanup-old-users'
      path: '/api/public/hooks/cleanup-old-users'
      fullPath: '/api/public/hooks/cleanup-old-users'
      preLoaderRoute: typeof ApiPublicHooksCleanupOldUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  MealBuilderRoute: MealBuilderRoute,
  ProgressRoute: ProgressRoute,
  ModulesIndexRoute: ModulesIndexRoute,
  ModulesModuleIdLessonIdRoute: ModulesModuleIdLessonIdRoute,
  ModulesModuleIdQuizRoute: ModulesModuleIdQuizRoute,
  ApiPublicHooksCleanupOldUsersRoute: ApiPublicHooksCleanupOldUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
