name: Keep Supabase Alive

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Supabase
        run: |
          curl -I https://ngktjdmfhvceniikjgpz.supabase.co
